### PR TITLE
COMP: Pip install Instances required to compilation (AMASSS, ALI_CBCT)

### PR DESCRIPTION
**Pull request by lucanchling**
@luciacev

### CODE REVIEW

**Comment by luciacev** [comment]
@ allemangD @jcfr @lucanchling 
After Luc removed the "pip installs , the tools do not run properly in MacOS ( run ok in Windows)  and the Slicer error seems to  indicate  that having removed the pip install may be causing issues. Can you please review Luc's commit 5 days ago  and let us know if this change is adequate or provide feedback to Luc? Thanks so much!

**Comment by luciacev** [comment]
@allemangD
After Luc removed the "pip installs , the tools do not run properly in MacOS ( run ok in Windows) and the Slicer error seems to indicate that having removed the pip install may be causing issues. Can you please review Luc's commit 5 days ago and let us know if this change is adequate or provide feedback to Luc? Thanks so much!

**Comment by lucanchling** [comment]
As Lucia mentioned, we've tried to run the different modules with a fresh version of Slicer (after uninstalling/reinstalling, the PythonSlicer would have only the packages furnished with Slicer) and the compilation wasn't running because of ImportErrors.
This happens on Linux as well as on MacOS and those two commits are here to correct the ImportErrors on AMASSS and ALICBCT modules.
I'm still trying to fix the compilation of ALI_IOS on MacOS...
Thanks for reviewing @allemangD @luciacev

**Comment by lucanchling** [comment]
I've just added a commit for fixing the compilation of ALI IOS on MacOS
I will just have to run some test with a fresh version of Slicer on the different OS to see if the changes that I've made doesn't affect the others
Let's wait until I've run those tests before merging this PR.

**Comment by allemangD** [comment]
@luciacev @lucanchling I apologize - in hindsight I should have triple-checked which packages are in fact available to Slicer by default.

After removing the `pip_installs` and replacing only those which are truly necessary, I would go ahead and merge this PR once your testing is completed.

I've checked out this branch and tested on my linux machine; after the latest changes I can correctly load all the modules in a fresh Slicer install.

**Comment by lucanchling** [comment]
Thanks so much for those comments @allemangD

**Comment by juanprietob** [comment]
@allemangD I reviewed the code and it looks fine but we need your input for the merge.

**Comment by allemangD** [comment]
:+1: thanks for merging Juan

**Pull request merged**
