### PR TITLE
FIX : error import

### PR DESCRIPTION
**Pull request by GaelleLeroux**
Hi @allemangD !

In Slicer preview SlicerAutomatedDentalsTools cannot be built because the CondaSetUp import failed. I've tried to fix it, can you tell me if it will work and if so merge it ? 

Thank you !
Gaelle

### CODE REVIEW

**Comment by allemangD** [comment]
We should apply this for consistency, but it is already applied in the extensions index. I don't expect this to fix any error.

https://github.com/Slicer/ExtensionsIndex/blob/main/AutomatedDentalTools.json#L3

> SlicerAutomatedDentalsTools cannot be built

Are you trying to build locally with CMake? You'll need to install SlicerConda for your development environment manually.

**Review by allemangD — APPROVED** [review]

**Comment by GaelleLeroux** [comment]
No I didn't tried to build it locally. Creating a Slicer local build to test our extension is very long and the one we're having is not accessible right now. I tried to fix it quickly based on the error in the dashboard but you're right I sould try to build it locally with CMake

**Comment by GaelleLeroux** [comment]
@allemangD 

I tried to change the name of the project to be consistent with th eAutomatedDentalsTools.json file in Slicer/ExtensionIndex. I'm not having any error building it manually and the error we saw in the dashborad seems to be link to the json. 
What do you think ? Do you think it will work ? If so can you merge it ?

**Review by allemangD — APPROVED** [review]

**Comment by allemangD** [comment]
Thanks @GaelleLeroux - merging now.

For reference the current dashboard is https://slicer.cdash.org/viewBuildError.php?buildid=3392250; since the ExtensionsIndex has `AutomatedDentalTools.json` I agree that this should fix the issue.

**Pull request merged**
